version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: ingemark
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgresdb
    ports:
      - '5432:5432'